(function(){
  const root=document.querySelector('[data-news-list]'),article=document.querySelector('[data-article]');
  const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const date=s=>new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric'}).format(new Date(s+'T00:00:00'));
  fetch('posts.json').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(posts=>{
    posts.sort((a,b)=>b.published.localeCompare(a.published));
    if(root){const tags=[...new Set(posts.flatMap(p=>p.tags))],controls=document.querySelector('[data-tag-list]');const render=tag=>{const shown=tag?posts.filter(p=>p.tags.includes(tag)):posts;root.innerHTML=shown.map(p=>`<article class="post-card"><time datetime="${esc(p.published)}">${date(p.published)}</time><h2><a href="article.html?id=${encodeURIComponent(p.id)}">${esc(p.title)}</a></h2><p>${esc(p.summary)}</p><div>${p.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')}</div></article>`).join('')||'<p class="empty">このタグの記事はまだありません。</p>'};controls.innerHTML=['すべて',...tags].map((t,i)=>`<button class="tag-button" type="button" data-tag="${i?esc(t):''}" aria-pressed="${i?'false':'true'}">${esc(t)}</button>`).join('');controls.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;controls.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');render(b.dataset.tag)});render('')}
    if(article){const id=new URLSearchParams(location.search).get('id'),p=posts.find(x=>x.id===id);if(!p){article.innerHTML='<h1>記事が見つかりません</h1><p><a href="index.html">更新情報の一覧へ戻る</a></p>';return}document.title=p.title+'｜まちの健康・医療案内';article.innerHTML=`<div class="eyebrow">更新情報</div><h1>${esc(p.title)}</h1><p class="article-meta">公開：<time datetime="${esc(p.published)}">${date(p.published)}</time>${p.updated!==p.published?`　更新：<time datetime="${esc(p.updated)}">${date(p.updated)}</time>`:''}</p><div class="tag-list">${p.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="article-body">${p.body.map(b=>`<section><h2>${esc(b.heading)}</h2>${b.paragraphs.map(x=>`<p>${esc(x)}</p>`).join('')}</section>`).join('')}</div><section class="section"><h2>関連するページ</h2><div class="related-grid">${p.related.map(x=>`<a class="related-card" href="${esc(x.url)}">${esc(x.title)} →</a>`).join('')}</div></section>`}
  }).catch(()=>{if(root)root.innerHTML='<p class="empty">更新情報を読み込めませんでした。時間をおいてもう一度お試しください。</p>';if(article)article.innerHTML='<h1>記事を読み込めませんでした</h1>'});
})();
